import { DatabaseSync } from "node:sqlite";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { getAuditKnowledgeBatch } from "../src/knowledge.mjs";

const args=new Map();
for(let i=2;i<process.argv.length;i+=1){
  const arg=process.argv[i];
  if(!arg.startsWith("--"))continue;
  const [key,inline]=arg.slice(2).split("=",2);
  if(inline!==undefined)args.set(key,inline);
  else if(process.argv[i+1]&&!process.argv[i+1].startsWith("--"))args.set(key,process.argv[++i]);
  else args.set(key,"true");
}

const taxonomyPath=resolve(
  args.get("taxonomy")||
  process.env.LIFECARDS_TAXONOMY_DB||
  "./data/eukaryota.sqlite"
);
const qualityPath=resolve(
  args.get("output")||
  process.env.LIFECARDS_CARD_QUALITY_DB||
  "./data/card-quality.sqlite"
);
const reportPath=resolve(
  args.get("report")||
  "./data/card-quality-report.json"
);
const AUDIT_RESOLVER_VERSION="v9-best-attributed-media";
const statusOnly=args.get("status")==="true";
const auditAll=args.get("all")==="true";
const defaultBatch=Math.max(1,Number(process.env.LIFECARDS_AUDIT_BATCH||250));
const limit=auditAll?Number.MAX_SAFE_INTEGER:Math.max(1,Number(args.get("limit")||defaultBatch));
const concurrency=Math.max(1,Math.min(6,Number(args.get("concurrency")||process.env.LIFECARDS_AUDIT_CONCURRENCY||3)));

if(!existsSync(taxonomyPath)){
  console.error("Gameplay taxonomy not found:",taxonomyPath);
  console.error("Run npm run sync:col first.");
  process.exit(1);
}

mkdirSync(dirname(qualityPath),{recursive:true});
const taxonomy=new DatabaseSync(taxonomyPath,{readOnly:true});
taxonomy.exec("PRAGMA query_only=ON");

function tableExists(db,name){
  return Boolean(
    db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(String(name))
  );
}

function taxonomyMeta(key){
  if(!tableExists(taxonomy,"meta"))return null;
  return taxonomy.prepare("SELECT value FROM meta WHERE key=?").get(String(key))?.value??null;
}

if(!tableExists(taxonomy,"taxa")){
  console.error("");
  console.error("LifeCards card audit cannot start: the gameplay taxonomy DB has no 'taxa' table.");
  console.error("Database:",taxonomyPath);
  console.error("Rebuild it with: npm run sync:col");
  taxonomy.close();
  process.exit(1);
}

if(!tableExists(taxonomy,"drop_pool")||!tableExists(taxonomy,"drop_pool_stats")){
  const schema=taxonomyMeta("schema_version")||"unknown";
  const scope=taxonomyMeta("scope")||"unknown";
  console.error("");
  console.error("LifeCards card audit cannot start: this gameplay taxonomy has no drop pool.");
  console.error("Database:",taxonomyPath);
  console.error("Schema:",schema,"· Scope:",scope);
  console.error("");
  console.error("This usually means eukaryota.sqlite was generated by an older LifeCards version");
  console.error("or the map-only database is being used as LIFECARDS_TAXONOMY_DB.");
  console.error("");
  console.error("Fix:");
  console.error("  npm run sync:col");
  console.error("");
  console.error("Then run:");
  console.error("  npm run audit:cards:status");
  console.error("  npm run audit:cards");
  taxonomy.close();
  process.exit(2);
}

const quality=new DatabaseSync(qualityPath);
quality.exec(`
  PRAGMA journal_mode=WAL;
  CREATE TABLE IF NOT EXISTS card_quality(
    taxon_id TEXT PRIMARY KEY,
    scientific_name TEXT NOT NULL,
    common_name TEXT,
    rank TEXT,
    rarity TEXT,
    status TEXT NOT NULL,
    reason TEXT,
    media_url TEXT,
    media_source TEXT,
    media_resolver TEXT,
    media_confidence TEXT,
    media_creator TEXT,
    media_license TEXT,
    wikipedia_url TEXT,
    wikidata_id TEXT,
    ncbi_tax_id TEXT,
    resolver_version TEXT,
    checked_at INTEGER NOT NULL
  );
  CREATE INDEX IF NOT EXISTS card_quality_status_idx ON card_quality(status);
  CREATE INDEX IF NOT EXISTS card_quality_rarity_status_idx ON card_quality(rarity,status);
  CREATE TABLE IF NOT EXISTS meta(
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
  );
`);

const qualityColumns=new Set(
  quality.prepare("PRAGMA table_info(card_quality)").all().map(row=>row.name)
);
if(!qualityColumns.has("resolver_version")){
  quality.exec("ALTER TABLE card_quality ADD COLUMN resolver_version TEXT");
}

try{
  taxonomy.prepare("ATTACH DATABASE ? AS qualitydb").run(qualityPath);
}catch(error){
  console.error("Unable to attach quality DB:",error.message);
  taxonomy.close();
  quality.close();
  process.exit(1);
}

function scalar(db,sql,...params){
  return Number(db.prepare(sql).get(...params)?.value||0);
}

function totalDroppable(){
  return scalar(taxonomy,"SELECT COUNT(*) AS value FROM drop_pool");
}

function stats(){
  const total=totalDroppable();
  const rows=taxonomy.prepare(`
    SELECT q.status AS status, COUNT(*) AS count
    FROM drop_pool p
    JOIN qualitydb.card_quality q ON q.taxon_id = p.taxon_id
    WHERE q.resolver_version = ?
    GROUP BY q.status
    ORDER BY q.status
  `).all(AUDIT_RESOLVER_VERSION);

  const byStatus=Object.fromEntries(rows.map(row=>[row.status,Number(row.count)]));
  const checked=Object.values(byStatus).reduce((a,b)=>a+b,0);
  return {
    totalDroppable:total,
    checked,
    unchecked:Math.max(0,total-checked),
    ready:byStatus.READY||0,
    review:byStatus.REVIEW||0,
    noImage:byStatus.NO_IMAGE||0,
    badData:byStatus.BAD_DATA||0,
    error:byStatus.ERROR||0,
    complete:total>0&&checked>=total,
    byStatus,
    resolverVersion:AUDIT_RESOLVER_VERSION,
    taxonomyScope:taxonomyMeta("scope")||"unknown",
    taxonomyDataset:taxonomyMeta("dataset_key")||"unknown",
    taxonomyImportedAt:taxonomyMeta("imported_at")||null,
  };
}

function reasonBreakdown(status){
  return taxonomy.prepare(`
    SELECT q.reason AS reason, COUNT(*) AS count
    FROM drop_pool p
    JOIN qualitydb.card_quality q ON q.taxon_id=p.taxon_id
    WHERE q.resolver_version=? AND q.status=?
    GROUP BY q.reason
    ORDER BY count DESC, q.reason
    LIMIT 12
  `).all(AUDIT_RESOLVER_VERSION,status);
}

function printStats(label="Card quality"){
  const value=stats();
  console.log("");
  console.log(label);
  console.log("─".repeat(52));
  console.log(`Droppable taxa : ${value.totalDroppable.toLocaleString()}`);
  console.log(`Checked        : ${value.checked.toLocaleString()}`);
  console.log(`READY          : ${value.ready.toLocaleString()}`);
  console.log(`REVIEW         : ${value.review.toLocaleString()}`);
  console.log(`NO_IMAGE       : ${value.noImage.toLocaleString()}`);
  console.log(`BAD_DATA       : ${value.badData.toLocaleString()}`);
  console.log(`ERROR          : ${value.error.toLocaleString()}`);
  console.log(`Unchecked      : ${value.unchecked.toLocaleString()}`);
  console.log(`Complete       : ${value.complete?"yes":"no"}`);

  if(value.review){
    console.log("");
    console.log("Top REVIEW reasons");
    console.log("─".repeat(52));
    for(const row of reasonBreakdown("REVIEW")){
      console.log(`${Number(row.count).toLocaleString().padStart(7)} · ${row.reason||"(no reason)"}`);
    }
  }

  if(value.noImage){
    console.log("");
    console.log("Top NO_IMAGE reasons");
    console.log("─".repeat(52));
    for(const row of reasonBreakdown("NO_IMAGE")){
      console.log(`${Number(row.count).toLocaleString().padStart(7)} · ${row.reason||"(no reason)"}`);
    }
  }

  return value;
}

if(statusOnly){
  const value=printStats();
  writeFileSync(reportPath,JSON.stringify({
    generatedAt:new Date().toISOString(),
    taxonomyPath,
    qualityPath,
    ...value,
  },null,2));
  taxonomy.close();
  quality.close();
  process.exit(0);
}

const rows=taxonomy.prepare(`
  SELECT
    p.taxon_id AS id,
    p.rarity,
    t.scientific_name,
    t.canonical_name,
    t.common_name,
    t.authorship,
    t.rank,
    t.status AS taxonomic_status
  FROM drop_pool p
  JOIN taxa t ON t.id=p.taxon_id
  WHERE p.taxon_id NOT IN (
    SELECT taxon_id
    FROM qualitydb.card_quality
    WHERE resolver_version = ?
  )
  ORDER BY
    CASE p.rarity
      WHEN 'MYTHIC' THEN 1
      WHEN 'LEGENDARY' THEN 2
      WHEN 'ULTRA_RARE' THEN 3
      WHEN 'SUPER_RARE' THEN 4
      WHEN 'RARE' THEN 5
      WHEN 'UNCOMMON' THEN 6
      ELSE 7
    END,
    p.slot
  LIMIT ?
`).all(AUDIT_RESOLVER_VERSION,limit);

if(!rows.length){
  printStats("Nothing left to audit");
  taxonomy.close();
  quality.close();
  process.exit(0);
}

const upsert=quality.prepare(`
  INSERT INTO card_quality(
    taxon_id,scientific_name,common_name,rank,rarity,status,reason,
    media_url,media_source,media_resolver,media_confidence,
    media_creator,media_license,wikipedia_url,wikidata_id,ncbi_tax_id,resolver_version,checked_at
  )
  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
  ON CONFLICT(taxon_id) DO UPDATE SET
    scientific_name=excluded.scientific_name,
    common_name=excluded.common_name,
    rank=excluded.rank,
    rarity=excluded.rarity,
    status=excluded.status,
    reason=excluded.reason,
    media_url=excluded.media_url,
    media_source=excluded.media_source,
    media_resolver=excluded.media_resolver,
    media_confidence=excluded.media_confidence,
    media_creator=excluded.media_creator,
    media_license=excluded.media_license,
    wikipedia_url=excluded.wikipedia_url,
    wikidata_id=excluded.wikidata_id,
    ncbi_tax_id=excluded.ncbi_tax_id,
    resolver_version=excluded.resolver_version,
    checked_at=excluded.checked_at
`);

function classify(row,knowledge){
  const scientific=String(row.scientific_name||"").trim();
  const rank=String(row.rank||"").trim();
  if(!scientific||!rank){
    return {status:"BAD_DATA",reason:"missing scientific name or rank"};
  }

  const media=knowledge?.media||null;
  if(!media?.imageUrl){
    return {status:"NO_IMAGE",reason:"no reusable licensed image resolved"};
  }

  const requiredAttribution=Boolean(media.creator&&media.license&&media.originalUrl);
  if(!requiredAttribution){
    return {status:"REVIEW",reason:"image found but attribution metadata incomplete"};
  }

  const confidence=String(media.confidence||"LOW").toUpperCase();
  if(confidence==="HIGH"){
    return {status:"READY",reason:"high-confidence taxon-linked licensed image"};
  }

  return {
    status:"REVIEW",
    reason:`image requires review (${media.resolver||"unknown resolver"} / ${confidence})`,
  };
}

function cleanAuditQuery(row){
  const rank=String(row.rank||"").toLowerCase().trim();
  let value=String(row.canonical_name||row.scientific_name||"").trim();
  const authorship=String(row.authorship||"").trim();

  if(authorship&&value.toLowerCase().endsWith(authorship.toLowerCase())){
    value=value.slice(0,value.length-authorship.length).trim();
  }

  const authorish=/\b\d{4}\b|\bemend\.?\b|\bsensu\b|\bex\b|\bet al\.?\b|\bCavalier-Smith\b/i;
  if(authorish.test(value)){
    if(["species","subspecies","variety","subvariety","form","subform"].includes(rank)){
      const match=value.match(/^([A-ZÀ-ÖØ-Þ][\p{L}.-]+\s+[a-z][\p{L}.-]+(?:\s+[a-z][\p{L}.-]+)?)/u);
      if(match)value=match[1];
    }else{
      value=value.split(/\s+/)[0];
    }
  }

  return value||String(row.scientific_name||"").trim();
}

let processed=0;
const runStarted=Date.now();
const auditBatchSize=Math.max(10,Math.min(50,Number(args.get("batch-size")||40)));

for(let offset=0;offset<rows.length;offset+=auditBatchSize){
  const chunk=rows.slice(offset,offset+auditBatchSize);
  const entries=chunk.map((row)=>({
    id:String(row.id),
    query:cleanAuditQuery(row),
  }));

  let resolved={};
  try{
    resolved=await getAuditKnowledgeBatch(entries,{lang:"en"});
  }catch{
    resolved={};
  }

  for(const row of chunk){
    const knowledge=resolved[String(row.id)]||null;
    const classification=classify(row,knowledge);
    const media=knowledge?.media||null;

    upsert.run(
      String(row.id),
      row.scientific_name,
      row.common_name||row.canonical_name||row.scientific_name,
      row.rank||"",
      row.rarity||"",
      classification.status,
      classification.reason,
      media?.imageUrl||null,
      media?.source||null,
      media?.resolver||null,
      media?.confidence||null,
      media?.creator||null,
      media?.license||null,
      knowledge?.wikipedia?.pageUrl||null,
      knowledge?.wikidata?.id||null,
      knowledge?.taxonomy?.ncbiTaxId||null,
      AUDIT_RESOLVER_VERSION,
      Date.now()
    );

    processed+=1;
    console.log(
      `[${processed}/${rows.length}] ${classification.status.padEnd(8)} · ${cleanAuditQuery(row)} · ${media?.resolver||"no-media"} · ${classification.reason}`
    );
  }

  if(offset+auditBatchSize<rows.length){
    await new Promise((resolve)=>setTimeout(resolve,180));
  }
}

const finalStats=stats();

if(finalStats.complete){
  quality.exec(`
    DROP TABLE IF EXISTS ready_drop_pool;
    DROP TABLE IF EXISTS ready_drop_pool_stats;
    CREATE TABLE ready_drop_pool(
      rarity TEXT NOT NULL,
      slot INTEGER NOT NULL,
      taxon_id TEXT NOT NULL,
      PRIMARY KEY(rarity,slot),
      UNIQUE(taxon_id)
    );
    CREATE TABLE ready_drop_pool_stats(
      rarity TEXT PRIMARY KEY,
      card_count INTEGER NOT NULL
    );
  `);

  quality.prepare("ATTACH DATABASE ? AS taxdb").run(taxonomyPath);
  try{
    quality.prepare(`
      INSERT INTO ready_drop_pool(rarity,slot,taxon_id)
      SELECT
        p.rarity,
        ROW_NUMBER() OVER (PARTITION BY p.rarity ORDER BY p.taxon_id),
        p.taxon_id
      FROM taxdb.drop_pool p
      JOIN card_quality q ON q.taxon_id = p.taxon_id
      WHERE q.status='READY' AND q.resolver_version=?
    `).run(AUDIT_RESOLVER_VERSION);

    quality.exec(`
      INSERT INTO ready_drop_pool_stats(rarity,card_count)
      SELECT rarity,COUNT(*)
      FROM ready_drop_pool
      GROUP BY rarity;
    `);
  } finally {
    quality.exec("DETACH DATABASE taxdb");
  }
}

quality.prepare(
  "INSERT OR REPLACE INTO meta(key,value) VALUES ('last_run_at',?)"
).run(new Date().toISOString());
quality.prepare(
  "INSERT OR REPLACE INTO meta(key,value) VALUES ('taxonomy_path',?)"
).run(taxonomyPath);
quality.prepare(
  "INSERT OR REPLACE INTO meta(key,value) VALUES ('taxonomy_scope',?)"
).run(String(finalStats.taxonomyScope||"unknown"));
quality.prepare(
  "INSERT OR REPLACE INTO meta(key,value) VALUES ('taxonomy_dataset',?)"
).run(String(finalStats.taxonomyDataset||"unknown"));
quality.prepare(
  "INSERT OR REPLACE INTO meta(key,value) VALUES ('taxonomy_imported_at',?)"
).run(String(finalStats.taxonomyImportedAt||""));
quality.prepare(
  "INSERT OR REPLACE INTO meta(key,value) VALUES ('resolver_version',?)"
).run(AUDIT_RESOLVER_VERSION);
quality.prepare(
  "INSERT OR REPLACE INTO meta(key,value) VALUES ('complete',?)"
).run(finalStats.complete?"1":"0");

const report={
  generatedAt:new Date().toISOString(),
  durationMs:Date.now()-runStarted,
  batchProcessed:processed,
  taxonomyPath,
  qualityPath,
  ...finalStats,
};
writeFileSync(reportPath,JSON.stringify(report,null,2));

printStats("Audit complete");
console.log("");
console.log("Report:",reportPath);
console.log("Quality DB:",qualityPath);
if(!finalStats.complete){
  console.log("Run npm run audit:cards again to continue, or npm run audit:cards:full for the remaining pool.");
}

taxonomy.close();
quality.close();
